services:
  app:
    build:
      context: ../../../backend/monthlyzip
      dockerfile: Dockerfile
      args:
        PROFILE: prod  # 빌드시 ARG PROFILE에 전달할 값
    image: monthlyzip-app
    container_name: monthlyzip-app
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    networks:
      - app-network
networks:
  app-network:
    external: true
