services:
  app:
    build:
      context: ../../../backend/monthlyzip
      dockerfile: Dockerfile
      args:
<<<<<<< HEAD
        PROFILE: prod  # 빌드시 ARG PROFILE에 전달할 값
=======
        PROFILE: prod
>>>>>>> bfc973d2df63ff798c3ade1e6236d752808e745c
    image: monthlyzip-app
    container_name: monthlyzip-app
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
<<<<<<< HEAD
=======
    volumes:
      - /home/ubuntu/images:/images  # 추가 : 이미지 디렉토리 마운트
>>>>>>> bfc973d2df63ff798c3ade1e6236d752808e745c
    restart: always
    networks:
      - app-network
networks:
  app-network:
    external: true
