services:
  react:
    image: react
    build:
      context: ../../../frontend/monthly-zip
      dockerfile: Dockerfile
    container_name: react
    ports:
      - "3000:80"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    external: true
