spring:
  datasource:
    url: jdbc:mysql://localhost:3306/monthlyzip
    driver-class-name: com.mysql.cj.jdbc.Driver

deploy:
  env: local

server:
  port: 8080

# 필요없을 듯?
app:
  baseUrl: http://localhost:8080