spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/monthlyzip
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

server:
  port: 8080

# 필요없을 듯?
app:
  baseUrl: http://localhost:8080