spring:
  datasource:
    url: jdbc:p6spy:mysql://mysql:3306/monthlyzip
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  data:
    redis:
      host: redis
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

app:
  baseUrl: https://j12d109.p.ssafy.io/
  imageDir: /inquiry/images/  # 스프링부트 컨테이너 내부 경로